server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id : route_1
          uri : http://localhost:8086/
          predicates:
            - Path = /users/**
        - id : route_2
          uri : http://localhost:8087/
          predicates:
            - Path = /offers/**

